### ISSUE TITLE
MPP HV2 5048 ..Hybrid 

### ISSUE THREAD

**Issue by tytower** [daromer2/InverterOfThings#1]
You said we could ask our questions here as an issue so :-
I'm looking for something to plug into my Inverter  and send data about 30 foot .
Reckon this is the way to go .
Will Try it but first just reassure me that if I plug this into my inverter its not going to go poof.
Too costly to bugger about with much .
I've got the esp and arduino knowledge OK, its only your program I would be concerned about.
I see there is no ".ino" file of any kind so the Arduino is just transferring your program onto the esp .

I've got a few 32's as well so would there be any need for me to debug or use a second serial port in any way?
How would I check if my inverter has power on the usb connection . Plug in a wire and check for a voltage on the brown wire?

**Comment by daromer2** [comment]
1. I will not assure anything. If you do something wrong it may go poof. Its a DIY product. 
2, Plenty of INO files:
![image](https://user-images.githubusercontent.com/14975395/104106892-fc94c380-52b8-11eb-8938-1bcf73f80cf1.png)
3.  Only debug if you want to debug. Its not needed for normal operation. 
4. You meassure your pins on your inverter and to see if you can use any output. 
5.
