### ISSUE TITLE
Not reading data from RJ45 port

### ISSUE THREAD

**Issue by ian-tait** [daromer2/InverterOfThings#4]
Hi,

I have been testing your serial connection on my inverter HYV4K4000-48, but seem to be having limited luck.
When using the MPI setting I can see the MQTT reports 0's on all topics.
However, if I use any other type like PIP and PCM, there are no topics being broadcast. Is this correct?

I wonder if I have the wrong pinout on my full-size adapter (rs232-TTL) (i.e. the adapter I'm using have the serial connector on the board. I have the mini ones on order.) My wiring is as shown in the image bottom right within GitHub.

If you have any suggestions I would love to hear them.

Thank you
Ian

**Comment by ian-tait** [comment]
So I seem to be getting ^0⧠ã on the _commandBuffer.
Not really sure why this would be the case.
It happens on all device types, which makes me think it is a reading issue within the code.

Any pointer would e really helpful about now. :)

Ian

**Comment by softwarecrash** [comment]
hey, the PIP/PCM seems not implementet fully on this fork.
i do a rework on another fork, but this supports only the qpigs command, not sure that your inverter replay to this. but you can try it

**Comment by daromer2** [comment]
PIP have now been implemented in this fork and support both PCM and PIP series.
