### ISSUE TITLE
Still sending P003PS Message when set on PIP

### ISSUE THREAD

**Issue by uploader18** [daromer2/InverterOfThings#5]
![mqttex](https://user-images.githubusercontent.com/42915702/118409053-e80e7080-b688-11eb-88e9-03ab0d60f9ae.jpg)
As commented on YT ready to test on multiple inverters. Sooo 

Debug serial: 

Command sent: P003PS Recieved data: (NAKss
Processing data from: P003PS
Sent Command: ^P006FPADJ
 Calc: 7373 Rx: 7373
Command sent: P006FPADJ Recieved data: (NAKss
Processing data from: P006FPADJ
Data sent to MQTT SERver - up: 0 days, 0 hours, 30 minutes, 47 seconds

![setting](https://user-images.githubusercontent.com/42915702/118409002-a5e52f00-b688-11eb-9878-07653ffe562c.jpg)

**Comment by uploader18** [comment]
found a problem in inverter.cpp

if (_nextCommandNeeded == "") {
      if (inverterType == 1)  _nextCommandNeeded = "P003GS"; //IF MPI we start with that order     **<-----invertertType must always compare to 1 since anything else will always be true**
      else _nextCommandNeeded = "QPIGS";  //if PIP/PCM

AND

 if (inverterType == 1) { Serial.print("^"); Serial1.print("^");}  //If MPI then prechar is needed **<-----same here**
    Serial.print(_nextCommandNeeded);
    Serial1.println(_nextCommandNeeded);

daromer2 please fix it :-D

**Comment by ninlee** [comment]
Was this sorted? I can't get information from my pip2424

**Comment by uploader18** [comment]
Hi! No it was not sorted from daromer2 side but i modified it by my self so i can send it to you.

**Comment by ninlee** [comment]
That would be great. Please do. Hopefully its the .bin.On Dec 16, 2021 8:14 AM, Žiga ***@***.***> wrote:
Hi! No it was not sorted from daromer2 side but i modified it by my self so i can send it to you.

**Comment by ninlee** [comment]
> Hi! No it was not sorted from daromer2 side but i modified it by my self so i can send it to you.

hey it would be great if you can send me that code.
I am new to this stuff so if you can send the .bin file that would be great.

**Comment by uploader18** [comment]
Give me a day since i have a lot of work in my company, will do it on sunday in my time zone(slovenia).

**Comment by ninlee** [comment]
Thanks man greatly appreciated

**Comment by ninlee** [comment]
> Give me a day since i have a lot of work in my company, will do it on sunday in my time zone(slovenia).

Any update?

**Comment by uploader18** [comment]
Sorry totaly forgot about you :-(
